### PR TITLE
Test & patch for shared interface & factory not being the same instance

### PR DESCRIPTION
**Pull request by cseufert**
I have found an issue where the factory instance that is created via dice, is not shared when creating that class manually. Please see newly added failing test case.

### CODE REVIEW

**Comment by cseufert** [comment]
Sorry, found a closed bug, #188 which shows a different way to do the factory.

Should it work both ways, or is it really about making the documentation more clear around the behaviour here.

**Comment by cseufert** [comment]
Not sure if this was a good idea to solve this problem, but it does work. Potentially a performance regression as it may not be caching the instances correctly now.

**Comment by cseufert** [comment]
Hi @TRPB ,

Is there any chance of getting this merged, or does it create more headaches than it solves?

-Chris

**Comment by cseufert** [comment]
If anyone is interested, I am now maintaining a fork here:
https://packagist.org/packages/moddengine/dice#v4.1.0

**Comment by TRPB** [comment]
Several of these are very large commits, would it be possible to create multiple, smaller PRs so they can be reviewed individually?

**Comment by cseufert** [comment]
Hi @TRPB,

sorry about this, the single patch turned into a fork of your library, with a few other changes, and suport for PHP8.

Are you intested in merging all of these features (should I create a PR for each feature?)

**Comment by garrettw** [comment]
@cseufert If you could make your PR from a branch other than `master` on your end, your fork's changes won't show up here and it will be easier to review.

**Pull request closed without merging**
