### PR TITLE
Fix bug when having an instance

### PR DESCRIPTION
**Pull request by solleer**
@TomBZombie Can you please merge this and release a new version?

### CODE REVIEW

**Comment by garrettw** [comment]
Can you explain the issue you were having before and why this fixes it?

**Comment by solleer** [comment]
When I would have a substitution with '['MaphperLoader\Json', 'getMaphper']' it would not create an instance of MaphperLoader\Json and would instead try to call it statically

**Comment by solleer** [comment]
@TomBZombie Can you merge this?

**Comment by solleer** [comment]
@TomBZombie Can you also release a new version after merging too?

**Comment by TomBZombie** [comment]
Can you provide a test that demonstrates the current version failing?

**Comment by solleer** [comment]
Can you release a version with the bug fix?

**Pull request merged**
