### PR TITLE
updated Dice.php line 233, because __toString deprecated in PHP 7.4.1…

### PR DESCRIPTION
**Pull request by MichaelBrenden**
…, must be getName

### CODE REVIEW

**Comment by MichaelBrenden** [comment]
__toString in PHP 7.4.1 deprecated per

https://github.com/php/php-src/commit/b964298c19c685f61542bbf30c49bd164b67c653

**Comment by TRPB** [comment]
I'll have to check which version getName was added in. I changed it from that to toString in an earlier commit because getName was only supported in the newest php versions at a time. Hopefully the depreciation means that getName is available in all supported php versions.

**Comment by jpirnat** [comment]
Is there a planned time frame for when this issue (i.e., issue #177) will be addressed?

**Comment by TRPB** [comment]
This couldn't be automatically merged due to the pull coming from an earlier branch so I haven't merged it.

I had also recently come across a bug when using `$args` and `constructParams` together which required changing this logic so this has now been fixed in master with a 4.0.2 release shortly.

**Pull request closed without merging**
