### PR TITLE
Fix bug with share

### PR DESCRIPTION
**Pull request by solleer**

### CODE REVIEW

**Comment by TRPB** [comment]
why is the second loop necessary? 

```php
if ($args) foreach ($args as $i => $arg) { // This if statement actually gives a ~10% speed increase when $args isn't set
                    // For variadic parameters, provide remaining $args
                 if ($param->isVariadic()) { $parameters = array_merge($parameters, $args); continue 2; }
					if ($class && ($arg instanceof $class || ($arg === null && $param->allowsNull()))) {
						// The argument matched, store it and remove it from $args so it won't wrongly match another parameter
						$parameters[] = array_splice($args, $i, 1)[0];
						// Move on to the next parameter
						continue 2;
					}
				}
                if ($share) foreach ($share as $i => $arg) {
                    if ($class && ($arg instanceof $class || ($arg === null && $param->allowsNull()))) {
                        // The argument matched, store it and remove it from $args so it won't wrongly match another parameter
                        $parameters[] = array_splice($share, $i, 1)[0];
                        // Move on to the next parameter
                        continue 2;
                    }
                }
			
```

This line: 

```php
			if ($share || isset($rule['constructParams'])) $args = array_merge($args, isset($rule['constructParams']) ? $this->expand($rule['constructParams'], $share) : []);
```

Merges `$args` and `$share` so they should be both included in the first loop.

**Comment by solleer** [comment]
The issue was that if you had a variadic method it would get passed everything from $share which is unexpected behavior. Shared objs should only be passed to where they are type hinted

**Comment by solleer** [comment]
That first line no longer merges `$share` into `$args`

**Comment by TRPB** [comment]
I've just  refactored this slightly to reduce the repeated code.

**Comment by TRPB** [comment]
This change will be quite a lot slower because it reads `isVariadic()` for every single argument. At minimum it would be better to put this in the cache array `$paramInfo` but it will still be slower than when `$param->isVariadic` was the last `if` block.

**Pull request merged**
